### ISSUE TITLE
Pandas 0.21.0 Breaks Many of the Tests

### ISSUE THREAD

**Issue by danielsclint** [BayAreaMetro/fast-trips#108]
The time comparisons get broken in 0.21.0:
- cannot set a Timedelta with a non-timedelta

Need to look at the Pandas changelog and see what happened.

**Comment by danielsclint** [comment]
Pandas 0.21.* changed the way the sum() aggregation functions worked on empty DataFrames. See Pandas Issues:
 - [9442](https://github.com/pandas-dev/pandas/issues/9422)
 - [15507](https://github.com/pandas-dev/pandas/pull/15507)

These fixes were somewhat reverted in Pandas 0.22.*. I added an updated version specification for the requirements.txt and .travis.yml file.

**Comment by e-lo** [comment]
This is working well on Travis
