### ISSUE TITLE
Implement Separate Arrive Early / Depart Late penalties

### ISSUE THREAD

**Issue by danielsclint** [BayAreaMetro/fast-trips#118]
The current code uses, ```preferred_delay_min``` to penalize departing later or arriving early depending on the travelers time target. The current implementation applies the same factor to each end. This ticket is separate this functionality into discrete components for arrive early and depart late.

**Comment by danielsclint** [comment]
These are now separated and a test script implemented along with some documentation updates. May still refactor code to better isolate functions and prevent rewriting similar code more than once.

**Comment by e-lo** [comment]
@danielsclint  and @lmz : Just a note that it would be great to wrap this component up this week so we can see if it alleviates many of the problems we've encountered in calibration.

Please let me know how I can help.

**Comment by e-lo** [comment]
@danielsclint  - i think we can call this done?

**Comment by danielsclint** [comment]
Done with flexible_pat merge.
