### ISSUE TITLE
Verify Required and Optional Fields and Files

### ISSUE THREAD

**Issue by danielsclint** [BayAreaMetro/fast-trips#122]
In helping trouble shoot a problem with @andishehr, we've come across some optional files and fields that are not optional anymore. This issue will identify them, and record the resolution.

**Comment by danielsclint** [comment]
`stops_ft.py` became a required file. 

https://github.com/BayAreaMetro/fast-trips/blob/701134f0d55fc983f76bef24031b99b3cb199350/fasttrips/Stop.py#L90

**Comment by danielsclint** [comment]
The following GTFS Plus optional fields are not used by Fast-Trips at all.

stop_distance_travelled ?? Stops and Shapes

### Agency
* agency_lang
* agency_phone
* agency_fare_url

### Bike Access Links
* File Not Used

### Drive Access Point
* name
* hourly_cost
* max_cost
* type

### Drive Access FT
* elevation_gain
* population_density
* retail_density
* auto_capacity
* indirectness

### Fare Rules
* contains_id -- Will fatal if this field exists.

### Routes
* route_desc
* route_url
* route_color
* route_text_color

### Routes FT
* proof_of_payment
* percent_using_farebox

### Stop Times
* stop_headsign
* pickup_type
* drop_off_type
* timepoint

### Stop Times FT
* pay_at_station
* real_time_data
* front_board_only
* reliability
* level_boarding
* percent_using_farebox


### Stops
* stop_code
* stop_desc
* zone_id
* location_type
* parent_station
* stop_timezone
* wheelchair_boarding

### Stops FT
* shelter
* lighting
* bike_parking
* bike_share_station
* seating
* platform_height
* level_boarding
* off_board_payment
* number_loading_areas

### Transfer FT
* elevation_gain
* population_density
* retail_density
* auto_capacity
* indirectness
* schedule_precedence

### Trips
* trip_headsign
* trip_short_name
* block_id
* shape_id
* wheelchair_boarding
* bikes_allowed
* direction_id

### Vehicles FT
* vehicle_description
* number_of_doors
* vehicle_length
* platform_height
* propulsion_type
* wheelchair_capacity
* bicycle_capacity
* boarding_door
* fare_payment_method
* user_defined_fare_payment
* boarding_height
* door_time

### Walk Access FT
* elevation_gain
* population_density
* retail_density
* auto_capacity
* indirectness

### Zones
* zone_name

**Comment by e-lo** [comment]
@danielsclint : are you asking if `shape_dist_travelled` is required?  It is listed as optional in the [`stop_times.txt` GTFS-PLUS spec](https://github.com/osplanning-data-standards/GTFS-PLUS/blob/3ef7a003e60ea463c75ae406b414c11675e6783a/files/stop_times.md) 

- this bit of code makes it pretty clear that it is being read from GTFS-PLUS if it is there...  
https://github.com/BayAreaMetro/fast-trips/blob/c08367062a9a7812c5003a5cde90e1e881e668aa/fasttrips/Trip.py#L142

- but this bit makes it clear that it is optional
https://github.com/BayAreaMetro/fast-trips/blob/c08367062a9a7812c5003a5cde90e1e881e668aa/fasttrips/Trip.py#L268-L271

**Comment by e-lo** [comment]
@danielsclint  - are you asking if `shape_dist_traveled` should be optional? I believe it should be and think it is based on our example networks working and it not being in there.

**Comment by danielsclint** [comment]
This seems to be resolved at this point.
