### ISSUE TITLE
Understand hyperpathcost update criteria

### ISSUE THREAD

**Issue by bhargavasana** [BayAreaMetro/fast-trips#136]
Do we always update hyperpathcost when there is slight change in value because, logsum calculation lowers hyperpathcost? In other words, we do not have to check if the new hyperpathcost is lower than the current hyperpathcost.

https://github.com/BayAreaMetro/fast-trips/blob/3d348a187367f1672b4d1fc88ba6d9b6e936077a/src/hyperlink.cpp#L330

**Comment by e-lo** [comment]
Right.  In this instance it is just checking if it changed anything and if so, that means it could trigger putting stops back into the label stop queue to reconsider.

If we were going to flag a "wrong" direction, it should probably be in comparison to the MIN_COST.
