### ISSUE TITLE
Empty fare period start/end time should default to 0-24 not NaN.

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/fast-trips#143]
Per the GTFS-Plus specification, the columns for `start_time` and `end_time` for `fare_periods_ft.txt` should default to 0-24 if they are empty.  Right now they are defaulting to NaN.

**Comment by e-lo** [comment]
@danielsclint  - could you please look at/hopefully take care of this since you worked on the GTFS read-in most recently? thx

**Comment by danielsclint** [comment]
This is also fixed in flexible_pat branch. Need to fix one problem with the max_overlap before the branch is ready though. See PR thread for more details.

**Comment by danielsclint** [comment]
Resolved with merging of flexible_pat branch.
