### ISSUE TITLE
pathsfound csvs don't have all the paths found

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/fast-trips#145]
`pathsfound_links.csv` doesn't contain some of the paths that go from origin to destination that are found during labeling.  Rather, it seems to only keep ones that have been enumerated.  I'm not sure it is possible/realistic to output them before they are enumerated though...but would be useful.

An alternative would be to call it pathsenumerated so that we differentiate?

**Comment by lmz** [comment]
The paths are only really found (as in, links put together in sequence) during enumeration, so I don't think there's any opportunity to print paths before that point.

The hyperpath structure could be dumped to file before enumeration for debugging purposes, if that's useful...?

**Comment by e-lo** [comment]
> The hyperpath structure could be dumped to file before enumeration for debugging purposes, if that's useful...?

Its already there in the log file so probably not?

**Comment by e-lo** [comment]
Can we rename to "paths enumerated"? ;-)

**Comment by e-lo** [comment]
Fixed in https://github.com/BayAreaMetro/fast-trips/commit/af8e8421ea7b9e1b0d8b9cb4ccb04a2650e58c1b
