### ISSUE TITLE
PSRC Test fails because can't calculate preferred_delay_min

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/fast-trips#150]
The PSRC test fails on this line because it can't calculate a `var_value` for `preferred_delay_min`

https://github.com/BayAreaMetro/fast-trips/blob/37a10a05d99ba68ddc8d310c88854bf3bc90146d/fasttrips/PathSet.py#L1061

| weight_name  | weight_value  | var_value |
| ------------- | ------------- | ------------- |
| preferred_delay_min  |        0.038    |     NaN | 
| preferred_delay_min    |      0.038    |     NaN |

**Comment by e-lo** [comment]
I'm pretty sure this should now be `depart_late_min` but can you confirm?

**Comment by danielsclint** [comment]
You are correct. This was an artifact of the rebase not being clean. The offending rows have been removed in the hf_develop PR.
