### ISSUE TITLE
Remove or update currently irrelevant tests

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/fast-trips#153]
[ or make them relevant again ]

i.e. calculate_distance

**Comment by e-lo** [comment]
And test_pat_variation.py

**Comment by danielsclint** [comment]
At least for the test_gtfs_objects.py, the tests were changed back to an old version by the https://github.com/BayAreaMetro/fast-trips/commit/0e8fa7d7811361c504b514e7a355eb1aa2458828 commit this past Monday. I'll change them back now.
