### ISSUE TITLE
Chosen not a column in pathset_links_df

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/fast-trips#157]
`KeyError: 'chosen'`

triggered from:

https://github.com/BayAreaMetro/fast-trips/blob/0ba43bea0097a5ae1de6c1c8b23f9c4d4bd7dca7/fasttrips/Assignment.py#L807-L808

Triggered when running trace for a single sample which didn't have had a chosen path

`[INFO/MainProcess]       1 paths sought,      0 paths found of 1 paths total.`

**Comment by e-lo** [comment]
Also needed to add:

`num_passengers_arrived = 0` to the beginning of function `choose_paths_without_simulation`

**Comment by lmz** [comment]
LGTM!  👍
