### ISSUE TITLE
Info needed to propose README edits

### ISSUE THREAD

**Issue by ddorinson** [BayAreaMetro/fast-trips#164]
I see two areas in the README that need attention, but I don't have enough info to propose specific commits:

- Line 45 ends abruptly: "Right now Fast-Trips requires Python 2.7. It also"
- Line 110 has two URLs that are 404 since the re-naming of the examples.  Should these be Springfield A & B?  Or are they meant to point to the two "Example Viewer" files in the top of the Examples directory?

**Comment by lmz** [comment]
Fixed in https://github.com/BayAreaMetro/fast-trips/commit/e346642bc6f08223aa0faecb08c3a477f6c70ea7
