### ISSUE TITLE
min_path_prob & max_num_paths configuration parameters

### ISSUE THREAD

**Issue by AsadTanvir** [BayAreaMetro/fast-trips#188]
It's written in the FastTrips documentation that paths with probability less than the **min_path_probability** get dropped IF **max_num_paths** specified AND hit. But in the outputs it seems to have not following the instruction.
Say, for a simulation I specified max_num_paths =10 and min_path_probability= 0.05. But, it's not dropping the paths having either pf_probability or probability below the specified value. (image attached)

![image](https://user-images.githubusercontent.com/34921760/58431523-44cb8780-807c-11e9-99d9-0601025da8cd.png)

**Comment by e-lo** [comment]
From my read of the output, only 2 paths would meet the `min_path_probability` criteria, not 10.  If you set `max_num_paths` to 2 does it select the two highly-probable ones? 

If so, then we should make the behavior more clear in the documentation. Could you refer me to the documentation section that you used to make the determination? Thx!

**Comment by AsadTanvir** [comment]
Yes, if I set `max_num_paths` to 2, it generates top two paths here and doesn't show the other 8 paths which have probability below 0.05.
The documentation section I referred to is this: http://bayareametro.github.io/fast-trips/io.html#configuration-options-pathfinding

**Comment by e-lo** [comment]
Ok, I think this is just a documentation clarification need. I just tried to address it in my latest push.
