### ISSUE TITLE
Replace TransitFeed with Partridge

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/fast-trips#85]
TransitFeed not python 3.5 compatible

**Comment by lmz** [comment]
Some alternative gtfs tools:
https://github.com/BayAreaMetro/awesome-transit#gtfs-libraries
https://github.com/luqmaan/awesome-transit#gtfs-libraries

**Comment by e-lo** [comment]
Two possibilities that use pandas dfs:
- https://github.com/remix/partridge
- https://github.com/araichev/gtfstk

**Comment by danielsclint** [comment]
Thanks @e-lo. It looks like Patridge might be the leader. I like that it is associated with a real project, Remix, and it has a decently active user base. I'll take a look in more detail later this week.

**Comment by danielsclint** [comment]
I'm heading down the path with Partridge. I had to make a few changes to Partridge to get it to work with Fast-Trips. Next step is Fast-Trips integration.

https://github.com/remix/partridge/pull/9

**Comment by e-lo** [comment]
Looks great!
