### ISSUE TITLE
Change simulation_iteration to a reset_bump_iter boolean.

### ISSUE THREAD

**Issue by danielsclint** [BayAreaMetro/fast-trips#99]
The simulation_iteration argument seems weird when running the calculate cost in stand-alone (static) mode. The simulation_iteration is only used to reset the bump_iter column on simulation_iteration 0. I argue in favor of a keyword arg for reset_bump_iter that the simulation loop can call as needed.

https://github.com/BayAreaMetro/fast-trips/blob/5e504cb3319b58faac3aca1310cb4ad08dc44ed8/fasttrips/PathSet.py#L665

**Comment by e-lo** [comment]
totally agreed.

**Comment by e-lo** [comment]
Clint - if your commit resolves this issue can you create a pull request so that I can test and merge it? thx!

**Comment by danielsclint** [comment]
This was addressed on Pull Request #100.
